export enum FieldType {
  Dropdown = 'dropdown',
  ShortText = 'shorttext',
  LongText = 'longtext',
  Name = 'name',
  Terms = 'terms',
  Choice = 'choice',
  Phone = 'phone',
  Email = 'email',
  Time = 'time',
  Checkbox = 'checkbox',
  Date = 'date',
  File = 'file',
  Gender = 'gender',
  Custom = 'custom',
  Divider = 'divider',
  Address = 'address',
  Heading = 'heading',
  Content = 'content',
}
